### ISSUE TITLE
Current To-Do

### ISSUE THREAD

**Issue by NikkyAI** [elytra/Center-of-the-Multiverse#5]
- [ ] Core 
  - [ ] add/remove: 
    - [ ] remove more overlaays
    - [ ] swap SoL for Nutrition
    - [ ] add fast leaf decay
  - [ ] Config: 
    - [ ] tinker smelt 1.5x per ore
    - [ ] whitelist BlockCarry for iron/quark chests
    - [ ] missing books for library and/or akashic
    - [ ] consider removing sorting mod
    - [ ] FTB Utils - Nerf chunk claim / load tickets
  - [ ] Ballance: 
    - [ ] keep an eye on everlasting abilities
- [ ] Client config: 
  - [ ] ship w/official server pre-saaved
  - [ ] custom main menu
  - [ ] default options
- [ ] Launcher:
  - [ ] windows exe launcher
- [ ] Bug:
  - [ ] hardcore death kills fruit contacts (probably also backpacks)
- [ ] Server maintenance:
  - [ ] clean server of client jars

**Comment by NikkyAI** [comment]
to build the server you can run
```
java -cp tools/launcher-builder.jar com.skcraft.launcher.builder.ServerCopyExport \
    --source modpacks/$PACK/src \
    --dest $upload_folder/
# ServerCopyExport also copies the .url.txt files
find "$upload_folder" -type f -name '*.url.txt' -delete
```

**Comment by AnsuzThurisaz** [comment]
ETA for maintenance run: 01/27/18

**Comment by AnsuzThurisaz** [comment]
Changes pushed and tested - version 2.0.2.2 - further changes pending
